In [9]:
import numpy as np

#scores for 6 students
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

#English
if np.isnan(english_score).sum() == 0:
    print('English has no nan')
    print('平均:', np.mean(english_score))
    print('最大值:', np.amax(english_score))
    print('最小值:', np.amin(english_score))
    print('標準差:', np.std(english_score))
else:
    print('English has nan')
    print('平均:', np.nanmean(english_score))
    print('最大值:', np.nanmax(english_score))
    print('最小值:', np.nanmin(english_score))
    print('標準差:', np.nanstd(english_score))
print() 

#math
if np.isnan(math_score).sum() == 0:
    print('math has no nan')
    print('平均:', np.mean(math_score))
    print('最大值:', np.amax(math_score))
    print('最小值:', np.amin(math_score))
    print('標準差:', np.std(math_score))
else:
    print('math has nan')
    print('平均:', np.nanmean(math_score))
    print('最大值:', np.nanmax(math_score))
    print('最小值:', np.nanmin(math_score))
    print('標準差:', np.nanstd(math_score))
print() 

#chinese
if np.isnan(chinese_score).sum() == 0:
    print('chinese has no nan')
    print('平均:', np.mean(chinese_score))
    print('最大值:', np.amax(chinese_score))
    print('最小值:', np.amin(chinese_score))
    print('標準差:', np.std(chinese_score))
else:
    print('chinese has nan')
    print('平均:', np.nanmean(chinese_score))
    print('最大值:', np.nanmax(chinese_score))
    print('最小值:', np.nanmin(chinese_score))
    print('標準差:', np.nanstd(chinese_score))


English has no nan
平均: 67.16666666666667
最大值: 89
最小值: 48
標準差: 13.433995020924426


math has nan
平均: 66.6
最大值: 85.0
最小值: 60.0
標準差: 9.707728879609279


chinese has no nan
平均: 75.33333333333333
最大值: 90
最小值: 65
標準差: 8.825468196582484


In [10]:
math_score[4] = 55
math_score

array([60., 85., 60., 68., 55., 60.])

In [12]:
#math
if np.isnan(math_score).sum() == 0:
    print('math has no nan')
    print('平均:', np.mean(math_score))
    print('最大值:', np.amax(math_score))
    print('最小值:', np.amin(math_score))
    print('標準差:', np.std(math_score))
else:
    print('math has nan')
    print('平均:', np.nanmean(math_score))
    print('最大值:', np.nanmax(math_score))
    print('最小值:', np.nanmin(math_score))
    print('標準差:', np.nanstd(math_score))
print() 

math has no nan
平均: 64.66666666666667
最大值: 85.0
最小值: 55.0
標準差: 9.860132971832694



In [16]:
a = np.corrcoef(chinese_score, english_score)
b = np.corrcoef(chinese_score, math_score)
print(a)
print(b)

if a[0,1]>b[0,1]:
    print('與國文成績相關係數最高的學科是英文')
else:
    print('與國文成績相關係數最高的學科是數學')

[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.74056803]
 [0.74056803 1.        ]]
與國文成績相關係數最高的學科是英文
