In [2]:
import numpy as np

array1 = np.array([[10, 8], [3, 5]])

#計算反矩陣，乘上原矩陣
array1_inv = np.linalg.inv(array1)
np.dot(array1, array1_inv)

array([[1., 0.],
       [0., 1.]])

In [4]:
#計算特徵值、特徵向量
e_value, e_vectors = np.linalg.eig(array1)
print(e_value)
print(e_vectors)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [6]:
#計算SVD
u, s, vh = np.linalg.svd(array1)
print(u)
print()
print(s)
print()
print(vh)
print()

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]

[13.94721714  1.86417116]

[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]

